# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

container:
  
  replicaCount: 3

  image:
    repository: <aws-account-id>.dkr.ecr.<aws-region>.amazonaws.com/<repository-name>
    tag: <image-tag>
    pullPolicy: Always
  
  port: 8080

  resources:
    limits:
      memory: "512Mi"
      cpu: "1"
    requests:
      memory: "256Mi"
      cpu: "0.5"

  probe:
    path: /
    livenessTimeOut: 5
    readinessDelay:  5

service:
  type: ClusterIP
  port: 80
  httpsPort: 443

ingress:
  enabled: true
  annotations: {}
  host: <app.company.co>
  paths: /

configmap:
  DATABASE_HOST: <exemple-variable>
  DATABASE_PORT: <exemple-variable>
  DATABASE_NAME: <exemple-variable>

secret:
  enabled: false
  external:
    - name: <env/app>
      keys: DATABASE_USER
    - name: <env/app>
      keys: DATABASE_PASSWORD
