apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "chart.fullname" . }}
  labels:
{{ include "chart.labels" . | indent 4 }}
data:
  {{- range $key, $value := .Values.configmap }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}