{{- if .Values.secret.enabled -}}
apiVersion: 'kubernetes-client.io/v1'
kind: ExternalSecret
metadata:
  name: {{ include "chart.fullname" . }}
  labels:
{{ include "chart.labels" . | indent 4 }}
secretDescriptor:
  backendType: secretsManager
  data: 
  {{- range .Values.secret.external }}
    - key: {{ .name }}
      name: {{ .keys }}
      property: {{ .keys }}
  {{- end }}
{{- end }}